language: cpp
sudo: required
dist: xenial

git:
  depth: false

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: 
      - CCCOMPILER=gcc-8
      - CXXCOMPILER=g++-8

before_script:
  - sudo add-apt-repository -y ppa:allegro/5.2
  - sudo apt-get update
  - sudo apt-get install -y git

script:
  - git clone --recursive --branch=master https://github.com/reworks/starlight.git build
  - cd build
  - chmod +x build.sh
  - sudo ./build.sh
  - make config=debug_linux64 all
  - make config=release_linux64 all