sudo: false 
dist: bionic

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

before_script:
  - git clone --recursive https://github.com/mosra/m.css.git mcss
  - sudo apt-get install python3-pip
  - pip3 install jinja2 Pygments
  - sudo apt-get -y install texlive-base texlive-latex-extra texlive-fonts-extra texlive-fonts-recommended

script:
  - cd mcss/documentation
  - ./doxygen.py ../../Doxyfile-mcss

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
