sudo: false 
dist: focal

branches:
  only:
    - master

# Thanks to: https://riptutorial.com/cmake/example/4723/configure-travis-ci-with-newest-cmake
install:
  - sudo apt update
  - sudo apt install doxygen
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.18.1/cmake-3.18.1-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.18.1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.18.1-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - git clone --recursive https://github.com/MaJerle/doxygen-dark-theme.git ddt

script:
  - mkdir build
  - cmake -G "Unix Makefiles" -DENABLE_DOXYGEN=ON -Bbuild_docs -H.
  - cd build_docs
  - make doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
