sudo: false 
dist: focal

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - cmake

install:
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal-rc main'
  - sudo apt update
  - sudo apt install cmake

before_script:
  - git clone --recursive https://github.com/MaJerle/doxygen-dark-theme.git ddt

script:
  - cmake .
  - cd build
  - make doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
