# This will run on Travis' 'new' container-based infrastructure
sudo: false 
dist: bionic

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen

before_script:
  - git clone --recursive https://github.com/mosra/m.css.git mcss
  - sudo apt-get install python3-pip
  - pip3 install jinja2 Pygments
  - sudo apt-get -y install \
    texlive-base \
    texlive-latex-extra \
    texlive-fonts-extra \
    texlive-fonts-recommended

# Build your code e.g. by calling make
script:
  - cd mcss/documentation
  - ./doxygen.py Doxyfile-mcss

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
