sudo: false 
dist: focal

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen
      - cmake

before_script:
  - git clone --recursive https://github.com/MaJerle/doxygen-dark-theme.git ddt

script:
  - apt update
  - apt install cmake
  - cmake .
  - cd build
  - make doxygen

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
