language: cpp
sudo: required
dist: trusty

services:
  - docker

git:
  depth: false

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7']
    env: COMPILER=g++-7
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['clang-6.0', 'g++-7']
    env: COMPILER=clang++-6.0
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: COMPILER=clang++
#  - os: osx
#    osx_image: xcode10.0
#    compiler: clang
#    env: COMPILER=clang++

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install liballegro5.2 && sudo apt-get install libxml2; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install allegro && brew install libxml2; fi

install:
  - git clone --recursive https://github.com/algorys/cmakeconverter.git
  - pip3 install -r cmakeconverter/requirements.txt
  - pip3 install cmakeconverter/
  - cmake-converter --solution=starlight.sln --std=c++17

script:
- cmake ..
- make