language: cpp
sudo: required
dist: xenial

git:
  depth: false

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: 
      - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      - COMPILER=g++-8
#    os: linux
#    compiler: clang
#    addons:
#      apt:
#        sources:
#          - llvm-toolchain-7
#        packages:
#          - clang-7
#    env: COMPILER=clang++-7.0

before_install:
# - pip install --user cpp-coveralls
- export CC=gcc-8
- export CXX=g++-8
- export COMPILER=g++-8

install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential git libsdl2-2.0-0 libsdl2-dev curl

before_script:
  - curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz
  - tar -xvzf premake5.tar.gz

script:
- ./premake5 --cc=gcc --os=linux --file=./premake5.lua --verbose gmake
- make config=debug_linux64 all
- make config=release_linux64 all