language: cpp
sudo: required
dist: xenial

services:
  - docker

git:
  depth: false

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    os: osx
    osx_image: xcode10.1
    compiler: clang
    env: CXXCOMPILER=clang++
    os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: 
      - CCCOMPILER=gcc-8
      - CXXCOMPILER=g++-8

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then docker pull ubuntu:18.04; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/reworks/starlight -td ubuntu:18.04 /bin/bash; fi

script:
  - if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "git clone --recursive --branch=master https://github.com/reworks/starlight.git reworks/starlight"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "cd reworks/starlight"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "./build-linux.sh"; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then git clone --recursive --branch=master https://github.com/reworks/starlight.git reworks/starlight; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cd reworks/starlight; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then ./build-macosx.sh; fi

after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then docker stop travis-ci; fi