language: cpp
sudo: required
dist: xenial

services:
  - docker

git:
  depth: false

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: 
      - CCCOMPILER=gcc-8
      - CXXCOMPILER=g++-8

before_install:
  - then docker pull ubuntu:18.04
  - then docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/reworks/starlight -td ubuntu:18.04 /bin/bash

script:
  - then docker exec -ti travis-ci bash -c "apt-get update"
  - then docker exec -ti travis-ci bash -c "apt-get install -y git"
  - then docker exec -ti travis-ci bash -c "git clone --recursive --branch=master https://github.com/reworks/starlight.git build"
  - then docker exec -ti travis-ci bash -c "cd build"
  - then docker exec -ti travis-ci bash -c "chmod +x build-linux.sh"
  - then docker exec -ti travis-ci bash -c "sudo ./build-linux.sh"
  - then docker exec -ti travis-ci bash -c "make config=debug_linux64 all"
  - then docker exec -ti travis-ci bash -c "make config=release_linux64 all"

after_success:
  - then docker stop travis-ci