sudo: false 
dist: bionic

branches:
  only:
    - master

addons:
  apt:
    packages:
      - doxygen

before_script:
  - git clone --recursive https://github.com/MaJerle/doxygen-dark-theme.git ddt

script:
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
