language: cpp
sudo: required
dist: xenial

git:
  depth: false

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-7
    env: COMPILER=g++-7
    os: linux
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
    env: COMPILER=g++-8
#    os: linux
#    compiler: clang
#    addons:
#      apt:
#        sources:
#          - llvm-toolchain-trusty-5.0
#        packages:
#          - clang-5.0
#    env: COMPILER=clang++-5.0
#    os: linux
#    compiler: clang
#    addons:
#      apt:
#        sources:
#          - llvm-toolchain-trusty-6.0
#        packages:
#          - clang-6.0
#    env: COMPILER=clang++-6.0
#    os: linux
#    compiler: clang
#    addons:
#      apt:
#        sources:
#          - llvm-toolchain-trusty-7.0
#        packages:
#          - clang-7.0
#    env: COMPILER=clang++-7.0

before_install:
    - pip install --user cpp-coveralls

install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential git libsdl2-2.0-0 curl

before_script:
  - curl -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-alpha13/premake-5.0.0-alpha13-linux.tar.gz
  - tar -xvzf premake5.tar.gz

script:
- ./premake5 --cc=$COMPILER --os=linux --file=./Quasar/premake5.lua --verbose gmake
- cd ./Quasar/build/ && make