language: cpp
sudo: required
dist: trusty

services:
  - docker

git:
  depth: false

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-7']
    env: COMPILER=g++-7
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
        packages: ['clang-6.0', 'g++-7']
    env: COMPILER=clang++-6.0
  - os: osx
    osx_image: xcode9.4
    compiler: clang
    env: COMPILER=clang++
#  - os: osx
#    osx_image: xcode10.0
#    compiler: clang
#    env: COMPILER=clang++

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then docker pull ubuntu:18.04; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker run --name travis-ci -v $TRAVIS_BUILD_DIR:/reworks/starlight -td ubuntu:18.04 /bin/bash; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install allegro && brew install libxml2; fi

install:
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "apt-get update"; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "apt-get install -y build-essential clang-6.0 g++-7 cmake git liballegro5.2 libxml2 python3 python3-pip"; fi

before_script:
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "git clone --recursive https://github.com/reworks/starlight.git"; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "git clone --recursive https://github.com/algorys/cmakeconverter.git"; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "pip3 install -r cmakeconverter/requirements.txt"; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "pip3 install cmakeconverter/"; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "cmake-converter --solution=starlight.sln --std=c++17"; fi
- if [ $TRAVIS_OS_NAME == osx ]; then git clone --recursive https://github.com/algorys/cmakeconverter.git; fi
- if [ $TRAVIS_OS_NAME == osx ]; then pip3 install -r cmakeconverter/requirements.txt; fi
- if [ $TRAVIS_OS_NAME == osx ]; then pip3 install cmakeconverter/; fi
- if [ $TRAVIS_OS_NAME == osx ]; then cmake-converter --solution=starlight/starlight.sln --std=c++17; fi

script:
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "cmake starlight/CMakeLists.txt"; fi
- if [ $TRAVIS_OS_NAME == linux ]; then docker exec -ti travis-ci bash -c "make starlight/"; fi
- if [ $TRAVIS_OS_NAME == osx ]; then cd starlight; fi
- if [ $TRAVIS_OS_NAME == osx ]; then cmake ..; fi
- if [ $TRAVIS_OS_NAME == osx ]; then make; fi

after_script:
- if [ $TRAVIS_OS_NAME == linux ]; then docker stop travis-ci; fi