version: 0.0.{build}-{branch}
branches: 
  only: 
    - master

shallow_clone: true
skip_tags: true
#clone_folder: c:\projects\reworks\starlight

image:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

#install:
#- cmd: build-windows.bat

build:
  parallel: true
  project: starlight.sln