version: 0.9.{build}-{branch}
branches: 
  only: 
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image:
  - Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - cmd: choco install opencppcoverage
  - cmd: choco install codecov
  - cmd: set path=C:\Program Files\OpenCppCoverage;%path%
  - cmd: git submodule update --init --recursive

matrix:
  fast_finish: false

build_script:
  - cmd: msbuild galaxy.sln

after_build:
  - cmd: coverage.bat