version: 0.9.{build}-{branch}
branches:
  only:
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image: Visual Studio 2019 Preview

platform:
  - x64

configuration:
  - Release

install:
  - cmd: git submodule update --init --recursive

matrix:
  fast_finish: false

build_script:
  - cmd: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DGALAXY_BUILD_TESTS=ON -DGALAXY_ENABLE_DOXYGEN=OFF -Bbuild -H.
  - cmd: cd build
  - cmd: msbuild galaxy_engine.sln

after_build:
  - cmd: cd ../
  - cmd: .\tests\bin\Release\tests.exe