version: 1.0.{build}-{branch}
branches: 
  only: 
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image:
  - Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive

matrix:
  fast_finish: false

build_script:
  - cmd: msbuild modules/zlib/build-VS2019-MT/zlib.sln
  - cmd: msbuild starmap.sln