version: 1.0.{build}-{branch}
branches: 
  only: 
    - master

shallow_clone: true
skip_tags: true

image:
  - Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:
  parallel: true
  project: protostar.sln