version: 0.0.{build}-{branch}
branches: 
  only: 
    - master

shallow_clone: false
skip_tags: true
clone_depth: 1

image:
  - Visual Studio 2019

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

install:
  - cmd: git submodule update --init --recursive

environment:
  matrix:
    fast_finish: true
  - solution_name: modules/zlib/build-VS2019-MT/zlib.sln
  - solution_name: starmap.sln

build_script:
  - cmd: msbuild %solution_name%