version: 0.0.{build}-{branch}
branches: 
  only: 
    - master

shallow_clone: false
skip_tags: true

image:
  - Visual Studio 2019

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

before_build:
  - cmd: update_submodule.bat
  - cmd: update_zlib_project_toolset.bat

build:
  parallel: true
  project: starmap.sln