name: linux

on:
  push:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      shell: bash
      uses: actions/checkout@v2

    - name: Checkout Submodules
      shell: bash
      run: git submodule update --init --recursive
