name: windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [windows-latest]
        platform: [x64]
        build_type: [Release]
        include:
          - os: windows-latest
            standard: 20

    steps:
      - uses: actions/checkout@v2

      - name: Configure
        run: cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -Bbuild -H.
        
      - name: Change Directory
        run: cd build

      - name: Build
        run: msbuild galaxy_engine.sln